CREATE TABLE IF NOT EXISTS users (
  id BIGINT NOT NULL AUTO_INCREMENT,
  sub VARCHAR(255) NOT NULL UNIQUE COMMENT 'auth0 subject',
  name VARCHAR(255),
  age INT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
INSERT INTO users (id, sub, name, age)
VALUES (1, '', 'Alice', 18);