version: "3.8"

services:
  db:
    image: mysql:8.0.37
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --authentication_policy=mysql_native_password
    volumes:
      - db:/var/lib/mysql

volumes:
  db:

networks:
  my_network:
    driver: bridge